version: '3'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_USER: 'myuser'
      MYSQL_PASSWORD: 'mypassword'
      MYSQL_ROOT_PASSWORD: 'myrootpassword'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork
    ports:
      - '3000:3306'

  app:
    build: .
    restart: always
    environment:
      DATABASE_URL: 'mysql://root:myrootpassword@localhost:3000/mydatabase'
    volumes:
      - .:/app
    ports:
      - '5000:5000'
    networks:
      - mynetwork
    depends_on:
      - db
    links:
      - db

volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge

